### PR TITLE
Fix where-object syntax older ps compat

### PR DESCRIPTION
**Pull request by eponerine**
Associated to issue #7

### CODE REVIEW

**Comment by eponerine** [comment]
Easy-peasy - Tested locally and everything was still working.

**Comment by JonnMsft** [comment]
This looks great! I should work on getting the new version up to PowerShell Gallery.

**Comment by eponerine** [comment]
Going to look at “new features” in the API next week or so and add them

**Comment by JonnMsft** [comment]
By the way, could I ask what is your scenario for using TeslaPSModule?

**Comment by eponerine** [comment]
Azure Function automation, specifically timer based triggers. 

Goal is to hook into some weather API and get car’s location’s weather at X o’clock. If below a threshold, warn user to plug it in at night. And at X o’clock, start preconditioning and heating car. 

Living in north east has been brutal so far. Frozen handles on the Model 3, etc.

**Pull request merged**
